### ISSUE TITLE
stripe-sync no longer works with a fresh run of `npm i`

### ISSUE THREAD

**Issue by tomhonour** [kaihendry/shopfront#9]
The script does not populate [https://dashboard.stripe.com/test/products](https://dashboard.stripe.com/test/products) anymore.

**Comment by kaihendry** [comment]
What was the fix?

**Comment by tomhonour** [comment]
Hi Kai, The fix was to delete the contents of `data` after cloning the git repo. `stripe-sync.sh` will fail if it uses the contents of `data` as it currently exists in this repo. `make clean` and then `make` will work however.
